### ISSUE TITLE
Leading zeroes are lost in numeric fields

### ISSUE THREAD

**Issue by bkaehny** [Snowflake-Labs/Excelerator#11]
I put this issue on this youtube video: https://www.youtube.com/watch?v=csmS5V2ONr8&lc=UgzpYpaSWOgSNDvBMbJ4AaABAg.9IDpIqerYoJ9IxW74-QrC0&feature=em-comments

You lost the leading zeroes in your ZIP code in rows 33 and 34 on the initial SELECT *. Is there any way to prevent that from happening?

**Comment by ssegal100** [comment]
Hi Brian. The leading zeros will not be lost if the column datatype in Snowflake is a string. In the example in the YouTube video, the datatype is a number, so that's why there are no leading zeros. In other words, the zip code in the table doesn't have the zeros.
Does this answer your question?
Thanks.

**Comment by bkaehny** [comment]
Yes, that answers my question. Thanks!
