### ISSUE TITLE
Cannot Clear Excelerator AddIn from Excel

### ISSUE THREAD

**Issue by terry-campbell-od** [Snowflake-Labs/Excelerator#22]
The AddIn was installed without checking the unblock property.  When this was attempted to be corrected the excel addin cannot be removed from excel.  Excel "keeps" finding it even after deleting all the excelerator files and unchecking the addin from the excel configuration.  Excel gives the message to remove the addin.  We click ok to remove it and uncheck the addin from the list.  The addin is not listed.  Excel is shutdown.  the laptop rebooted.  When Excel is started again, it finds the configuration for the previous addin.  No matter what we do we cannot get rid of that reference.   

We tired restoring the addin to the location excel is looking for and now excel is really acting weird.  It is displaying double addin icons and throwing errors.  See the attached screenshots.
[Snowflake errors.xlsx](https://github.com/Snowflake-Labs/Excelerator/files/6167261/Snowflake.errors.xlsx)

**Comment by ssegal100** [comment]
Terry,
This can be a little tricky. Excel might ask you to move the add-in to the user directory, so it might be hard to find. It can be stored in this directory C:\Users\<user>\AppData\Roaming\Microsoft\AddIns.
Sounds like you have two add-ins enabled. To delete both of them try this:
1 - Make sure all snowflake add-ins are checked in the add-in config window
![image](https://user-images.githubusercontent.com/13276366/111708383-bf4a3600-8813-11eb-9abe-e1ad62465757.png)

2 - Close the add-in window. Go to File --> Options --> Add-ins
You should be able to see where the add-ins are located. Make note of these locations because you will need to delete it in subsequent steps.
![image](https://user-images.githubusercontent.com/13276366/111708525-0506fe80-8814-11eb-9efe-1f078604f558.png)

3 - Go back to the step 1 and uncheck all Snowflake add-ins.
4 - Find all the the add-ins from step 2 and delete them.
5 - Open the Add-in config window in step 1. Check the add-ins and it should tell you that they can't be found and ask if you want to delete it. Say yes.
6 - You should now be able to add the add-in that is unblocked.
Let me know if this works for you.
Steve

**Comment by terry-campbell-od** [comment]
For the user with this issue - 

When I opened up Excel today I only had one instance of Excelerator. I ran a SQL and it worked. Then closed it down and ran it again and got the same error.

I followed the instructions below. I only saw one instance of Excelerator. I deleted it and started over and I still goet the error. The only odd think I see is that when I walk through the process the first time and close the

Excel file I get the runtime error below and it as me do I want to debug. I ignore it and close the file and get when I run the SQL I then get the compilation error. I don’t get that runtime error with anything else I use.
[20210319_Issue_22_Update.pdf](https://github.com/Snowflake-Labs/Excelerator/files/6171493/20210319_Issue_22_Update.pdf)
